jdk:
- openjdk8
- openjdk11

language: scala
scala:
- 2.13.0-RC1

script:
- sbt ++$TRAVIS_SCALA_VERSION laws/run test

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
